name: Comment Notification

on:
  issue_comment:
    types: [created]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "New Comment on Issue: ${{ github.event.issue.title }}"
          body: "Comment details: ${{ github.event.comment.body }}"
          to: ${{ steps.get_assignees.outputs.emails }}
          from: ${{ secrets.GMAIL_USERNAME }}
