name: Issue Handler

on:
  issues:
    types: [opened]

jobs:
  handle-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 最新のLTSバージョンを指定

      - name: Install dependencies
        run: npm install @actions/github @actions/core

      - name: Run JavaScript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./script/handle-issue.js
