name: Issue Labeler

on:
  issues:
    types: [opened]

permissions:
  issues: write  # コメントを追加するための権限を付与

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Label issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./script/label-issue.js
