name: Validate Inquiry Form

on:
  issues:
    types: [opened, edited]
    
permissions:
 issues: write
 contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug issue form validation
        run: |
          echo "Issue body:"
          echo "${{ github.event.issue.body }}"

          # 問い合わせ内容のバリデーション
          inquiry_content=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=問い合わせ内容: ).*')
          echo "Extracted inquiry_content: $inquiry_content"
          if [[ -z "$inquiry_content" ]]; then
            echo "問い合わせ内容が空です。再入力してください。"
            exit 1
          fi

          # 問い合わせ対応希望日のバリデーション
          inquiry_date=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=問い合わせ対応希望日: ).*')
          echo "Extracted inquiry_date: $inquiry_date"
          if [[ ! "$inquiry_date" =~ ^[0-9]{4}/[0-9]{2}/[0-9]{2}$ ]]; then
            echo "問い合わせ対応希望日がyyyy/mm/dd形式ではありません。再入力してください。"
            exit 1
          fi

      - name: Comment on issue
        if: failure()
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'フォームの入力に不備があります。問い合わせ内容が空でないか、または対応希望日がyyyy/mm/dd形式で入力されているかをご確認ください。'
            })

