name: Mention Issue Owner

on:
  workflow_dispatch: # 手動トリガーを追加

permissions:
  issues: write
  contents: write

jobs:
  mention:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Mention the issue owner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_OWNER=$(jq -r '.issue.user.login' < "${GITHUB_EVENT_PATH}")
        ISSUE_NUMBER=$(jq -r '.issue.number' < "${GITHUB_EVENT_PATH}")
        ISSUE_LABELS=$(curl -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}" | jq -r '.labels[].name')

        if echo "$ISSUE_LABELS" | grep -q "回答済み"; then
          COMMENT_BODY="こんにちは！！ @${ISSUE_OWNER}"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"body\": \"${COMMENT_BODY}\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments"
        fi

