name: Mention Issue Owner

on:
  schedule:
    - cron: '* * * * *' # 1分ごとに実行
  workflow_dispatch: # 手動トリガーを追加

jobs:
  mention:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Create package.json
      run: |
        echo '{
          "name": "mention-issue-owner",
          "version": "1.0.0",
          "description": "A GitHub Action to mention issue owners",
          "main": "mention-issue-owner.js",
          "scripts": {
            "start": "node ./script/mention-issue-owner.js"
          },
          "dependencies": {
            "@octokit/rest": "^18.0.0"
          }
        }' > package.json

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: npm start
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
