name: Mention Issue Owner

on:
  workflow_dispatch: # 手動トリガーを追加

permissions:
  issues: write
  contents: write

jobs:
  mention:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Mention the issue owner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # GitHubイベントデータを変数に格納
        EVENT_DATA=$(cat "${GITHUB_EVENT_PATH}")

        # ISSUE_OWNERを取得
        ISSUE_OWNER=$(echo "$EVENT_DATA" | jq -r '.issue.user.login')
        ISSUE_NUMBER=$(echo "$EVENT_DATA" | jq -r '.issue.number')

        # ISSUE_LABELSを取得
        ISSUE_LABELS=$(curl -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}" | jq -r '.labels[].name')

        # ラベルが「回答済み」の場合にコメントを投稿
        if echo "$ISSUE_LABELS" | grep -q "回答済み"; then
          COMMENT_BODY="こんにちは！！ @${ISSUE_OWNER}"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"body\": \"${COMMENT_BODY}\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments"
        fi
