name: Mention Issue Owner

on:
  workflow_dispatch: # 手動トリガーを追加

permissions:
  issues: write
  contents: write

jobs:
  mention:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Mention the issue owner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # リポジトリの全Issueを取得
        ISSUES=$(curl -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/issues?state=all")

        # 各Issueに対して処理を行う
        echo "$ISSUES" | jq -c '.[]' | while read -r ISSUE; do
          ISSUE_OWNER=$(echo "$ISSUE" | jq -r '.user.login')
          ISSUE_NUMBER=$(echo "$ISSUE" | jq -r '.number')
          ISSUE_LABELS=$(echo "$ISSUE" | jq -r '.labels[].name')

          # nullチェックを追加
          if [ "$ISSUE_OWNER" != "null" ] && [ "$ISSUE_NUMBER" != "null" ] && [ "$ISSUE_LABELS" != "null" ]; then
            # ラベルが「回答済み」の場合にコメントを投稿
            if echo "$ISSUE_LABELS" | grep -q "回答済み"; then
              COMMENT_BODY="こんにちは！！ @${ISSUE_OWNER}"
              curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
                -d "{\"body\": \"${COMMENT_BODY}\"}" \
                "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments"
            fi
          fi
        done
