name: Mention Issue Owner

on:
  schedule:
    - cron: '* * * * *' # 1分ごとに実行
  workflow_dispatch: # 手動トリガーを追加

jobs:
  mention-owner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List issues with "回答済み" label
      uses: actions/github-script@v6
      id: list-issues
      with:
        script: |
          const issues = await github.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: '回答済み',
            state: 'open'
          });
          return issues.data;

    - name: Mention issue owners
      uses: actions/github-script@v6
      with:
        script: |
          const issues = JSON.parse(process.env.ISSUES);
          for (const issue of issues) {
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: `@${issue.user.login} 回答未確認です。確認してリアクションお願いします。`
            });
          }
      env:
        ISSUES: ${{ steps.list-issues.outputs.result }}

